In [3]:
import numpy as np 
from scipy.linalg import null_space

In [19]:
#Matriz A
A = np.matrix([ [1,1,0], [1,1,0] ]) 
print("Matriz A: \n",A)
#Matriz B
B1 = np.matrix([ [1,1,1],[2,2,4],[2,3,5] ])
print("\nMatriz B: \n",B1)

ejemplo = np.matrix([ [1,2,3],[4,5,6],[7,8,9] ])
print("\nMatriz Ejemplo: \n",ejemplo)

Matriz A: 
 [[1 1 0]
 [1 1 0]]

Matriz B: 
 [[1 1 1]
 [2 2 4]
 [2 3 5]]

Matriz Ejemplo: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
#Calculo del nucleo de la matriz A y B

nucleo = null_space(A)
print("Nucleo de la matriz A:\n", nucleo)

nucleo2 = null_space(B1)
print("Nucleo de la matriz B:\n", nucleo2)

nucleo3 = null_space(ejemplo)
print("Nucleo de la matriz Ejemplo:\n", nucleo3)

Nucleo de la matriz A:
 [[-0.70710678  0.        ]
 [ 0.70710678  0.        ]
 [ 0.          1.        ]]
Nucleo de la matriz B:
 []
Nucleo de la matriz Ejemplo:
 [[-0.40824829]
 [ 0.81649658]
 [-0.40824829]]
